"""
JumpShip — Job evaluator and resume tailoring.

Uses LLMClient for all provider calls — provider-agnostic.
"""
from __future__ import annotations

from typing import Optional

from backend.services.llm_client import LLMClient


# ── JSON schema for job assessment ────────────────────────────────────────────

ASSESSMENT_SCHEMA = {
    "type": "object",
    "required": ["score", "summary", "strengths", "gaps", "suggestions",
                 "keywords_matched", "keywords_missing"],
    "properties": {
        "score":             {"type": "integer", "minimum": 0, "maximum": 100},
        "summary":           {"type": "string"},
        "strengths":         {"type": "array", "items": {"type": "string"}},
        "gaps":              {"type": "array", "items": {"type": "string"}},
        "suggestions":       {"type": "array", "items": {"type": "string"}},
        "keywords_matched":  {"type": "array", "items": {"type": "string"}},
        "keywords_missing":  {"type": "array", "items": {"type": "string"}},
    },
}

# ── Prompts ────────────────────────────────────────────────────────────────────

_ASSESSMENT_SYSTEM = (
    "You are an expert HR consultant and career coach specialising in resume "
    "optimisation and job matching. Analyse the candidate's resume against the "
    "job description and provide structured, actionable feedback. "
    "Respond ONLY with valid JSON — no markdown fences, no prose outside the JSON."
)

_ASSESSMENT_USER = """Analyse this resume against the job description below.

## RESUME
{resume}

## JOB DESCRIPTION
{job_description}
Job Title: {job_title} at {company_name}

Return EXACTLY this JSON structure (no extra keys, no markdown):
{{
  "score": <integer 0-100>,
  "summary": "<2-3 sentence fit summary>",
  "strengths": ["<strength with evidence>"],
  "gaps": ["<gap or missing requirement>"],
  "suggestions": ["<actionable improvement>"],
  "keywords_matched": ["<keyword found in resume>"],
  "keywords_missing": ["<keyword absent from resume>"]
}}"""

_TAILORED_RESUME_SYSTEM = (
    "You are a professional resume editor. Your ONLY task: take the candidate's existing "
    "resume text and the job description, then output a tightened, better-aligned resume "
    "in Markdown. You must not add commentary, footers, meta-notes, disclaimers, cover-letter "
    "text, watermarks, 'tailored for…' lines, AI attribution, or anything that is not part of "
    "a standard resume. Output Markdown body ONLY: start with the person's name as # heading, "
    "then resume sections. One printed page when rendered at normal density: be concise; "
    "prefer fewer bullets and shorter lines over dense walls of text. No HTML. No tables "
    "unless absolutely necessary."
)

_TAILORED_RESUME_USER = """You will compare the ORIGINAL RESUME to the TARGET JOB and produce ONE revised resume in Markdown.

## ORIGINAL RESUME (source of truth; do not fabricate facts)
{resume}

## TARGET JOB (for alignment only)
Title: {job_title} at {company_name}
{job_description}

## CANDIDATE CONTEXT (contact and preferences; use only what helps the resume)
{candidate_context}

## PRIOR FIT SIGNALS (optional; do not repeat verbatim as prose)
Match score (0-100): {score}
Notable gaps vs posting: {gaps}
Useful keywords from posting still weak in resume: {missing_keywords}

OBJECTIVE
- Improve clarity and relevance to this job by reordering, rephrasing, and emphasizing what already exists.
- Address gaps only by reframing honest experience or skills already implied in the resume; never invent employers, dates, degrees, tools, or metrics.
- Keep standard sections (e.g. Summary/Profile, Experience, Education, Skills). Merge or shorten sections if needed to stay on one page.

STRICTLY FORBIDDEN (do not output any of these anywhere, including end of document)
- Footnotes, endnotes, "Notes:", "Disclaimer", "Generated by", model names, or system prompts
- Letters to the employer, salary discussion, or negotiation text
- URLs or text that were not present in the resume or candidate context (except you may format existing contact fields)
- More than one page worth of content: if too long, cut lowest-priority bullets first

MARKDOWN FORMAT
- # Full name (first line)
- ## Section headings; use - bullets for lists; ### only if needed
- No horizontal rules unless essential

Return ONLY the Markdown resume. No preamble after the rules. No closing line."""


# ── Public API ─────────────────────────────────────────────────────────────────

_ASSESSMENT_DEFAULTS = {
    "score": 0,
    "summary": "",
    "strengths": [],
    "gaps": [],
    "suggestions": [],
    "keywords_matched": [],
    "keywords_missing": [],
}


def assess_job(
    resume_text: str,
    job_description: str,
    job_title: str = "",
    company_name: str = "",
    client: Optional[LLMClient] = None,
) -> dict:
    """
    Assess resume against job description.
    Returns dict: score, summary, strengths, gaps, suggestions, keywords_*.
    """
    llm = client or LLMClient.from_settings()

    user_prompt = _ASSESSMENT_USER.format(
        resume=resume_text[:8000],
        job_description=job_description[:6000],
        job_title=job_title,
        company_name=company_name,
    )

    result = llm.complete_json(_ASSESSMENT_SYSTEM, user_prompt, schema=ASSESSMENT_SCHEMA)

    for key, default in _ASSESSMENT_DEFAULTS.items():
        result.setdefault(key, default)

    try:
        result["score"] = max(0, min(100, int(result["score"])))
    except (TypeError, ValueError):
        result["score"] = 0

    return result


def analyse_resume(
    resume_text: str,
    job_description: str,
    job_title: str = "",
    company_name: str = "",
    provider: str = "",
    api_key: str = "",
) -> dict:
    """Legacy compat shim → assess_job."""
    return assess_job(
        resume_text=resume_text,
        job_description=job_description,
        job_title=job_title,
        company_name=company_name,
    )


def generate_tailored_resume(
    resume_text: str,
    job_description: str,
    job_title: str = "",
    company_name: str = "",
    analysis: Optional[dict] = None,
    provider: str = "",
    api_key: str = "",
) -> str:
    """Legacy compat shim → generate_tailored_resume_markdown."""
    return generate_tailored_resume_markdown(
        resume_text=resume_text,
        job_description=job_description,
        job_title=job_title,
        company_name=company_name,
        assessment=analysis,
    )


def generate_tailored_resume_markdown(
    resume_text: str,
    job_description: str,
    job_title: str,
    company_name: str,
    assessment: Optional[dict] = None,
    client: Optional[LLMClient] = None,
    user_profile: Optional[dict] = None,
) -> str:
    """
    Generate a Markdown-formatted tailored resume for a specific job.
    user_profile: dict from UserProfile DB row (name, email, phone, linkedin_url, etc.)
    Returns raw Markdown string.
    """
    llm = client or LLMClient.from_settings()

    a = assessment or {}
    gaps_list = list(a.get("gaps") or [])
    gaps = ", ".join(gaps_list[:5]) or "N/A"
    missing_kw = ", ".join((a.get("keywords_missing") or [])[:10]) or "N/A"
    score = a.get("match_score", a.get("score", "N/A"))

    candidate_context = _build_candidate_context(user_profile or {})

    user_prompt = _TAILORED_RESUME_USER.format(
        resume=resume_text[:8000],
        job_description=job_description[:5000],
        job_title=job_title,
        company_name=company_name,
        score=score,
        gaps=gaps,
        missing_keywords=missing_kw,
        candidate_context=candidate_context,
    )

    return llm.complete(_TAILORED_RESUME_SYSTEM, user_prompt)


def _build_candidate_context(p: dict) -> str:
    """Format UserProfile fields into a compact context block for the LLM."""
    lines = []
    if p.get("full_name"):
        lines.append(f"Name: {p['full_name']}")
    if p.get("email"):
        lines.append(f"Email: {p['email']}")
    if p.get("phone"):
        lines.append(f"Phone: {p['phone']}")
    if p.get("linkedin_url"):
        lines.append(f"LinkedIn: {p['linkedin_url']}")
    if p.get("github_url"):
        lines.append(f"GitHub: {p['github_url']}")
    if p.get("portfolio_url"):
        lines.append(f"Portfolio: {p['portfolio_url']}")
    location_parts = [p.get("location_city"), p.get("location_state"), p.get("location_country")]
    location = ", ".join(x for x in location_parts if x)
    if location:
        lines.append(f"Location: {location}")
    if p.get("preferred_work_mode") and p["preferred_work_mode"] != "any":
        lines.append(f"Preferred work mode: {p['preferred_work_mode']}")
    if p.get("willing_to_relocate"):
        lines.append("Willing to relocate: Yes")
    if p.get("salary_min") or p.get("salary_max"):
        currency = p.get("salary_currency", "BRL")
        lo = p.get("salary_min", "")
        hi = p.get("salary_max", "")
        sal = f"{currency} {lo}-{hi}" if lo and hi else f"{currency} {lo or hi}"
        lines.append(f"Salary expectation: {sal}/mo (context only; do not include in resume)")
    if p.get("work_authorization"):
        lines.append(f"Work authorization: {p['work_authorization']}")
    if p.get("highest_degree"):
        lines.append(f"Education: {p['highest_degree']}" + (f", {p['university']}" if p.get("university") else ""))
    return "\n".join(lines) if lines else "No additional candidate context provided."
