"""
JumpShip — Tailored resume generator.

Pipeline:
  ResumeProfile + JobResult + JobAssessment → LLM → Markdown → PDF (fpdf2)

fpdf2 is pure Python — no GTK, no system libs, works on Windows/Linux/Mac.
"""
from __future__ import annotations

import re
import uuid
from pathlib import Path
from typing import Optional

from backend.services.ai_evaluator import generate_tailored_resume_markdown
from backend.services.llm_client import LLMClient


def generate_pdf(
    resume_text: str,
    job_title: str,
    company_name: str,
    job_description: str,
    assessment: Optional[dict] = None,
    output_dir: Optional[Path] = None,
    client: Optional[LLMClient] = None,
    user_profile: Optional[dict] = None,
) -> tuple[Path, str]:
    """
    Generate a tailored resume PDF for a specific job.
    Returns (pdf_path, markdown_text).
    """
    from backend.config import settings

    out_dir = output_dir or Path(settings.resume_output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    llm = client or LLMClient.from_settings()
    md_text = generate_tailored_resume_markdown(
        resume_text=resume_text,
        job_description=job_description,
        job_title=job_title,
        company_name=company_name,
        assessment=assessment,
        client=llm,
        user_profile=user_profile,
    )
    md_text = _sanitize_resume_markdown(md_text)

    safe_company = re.sub(r"[^\w\-]", "_", company_name or "company")[:30]
    safe_title   = re.sub(r"[^\w\-]", "_", job_title   or "role")[:30]
    filename = f"resume_{safe_company}_{safe_title}_{uuid.uuid4().hex[:6]}.pdf"
    pdf_path = out_dir / filename

    _md_to_pdf(md_text, pdf_path)

    return pdf_path, md_text


def _sanitize_resume_markdown(raw: str) -> str:
    """
    Strip common model artifacts (fences, trailing footers, meta lines) so PDF stays clean.
    """
    text = (raw or "").strip()
    if not text:
        return text

    # Unwrap accidental ```markdown fences
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].lstrip().startswith("```"):
            lines = lines[1:]
        while lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    footer_re = re.compile(
        r"(?im)^(generated by|created (with|using)|tailored (for|to)|this (resume|cv) (was|is)|"
        r"version\s*\d+|chatgpt|openai|anthropic|claude|gemini|\bai\b.{0,12}assistant|"
        r"disclaimer|notes?:|footer:).*$"
    )
    lines = text.splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    while lines and footer_re.search(lines[-1].strip()):
        lines.pop()
        while lines and not lines[-1].strip():
            lines.pop()

    # Drop trailing horizontal rules that often precede junk paragraphs
    while lines and re.match(r"^[-*_]{3,}\s*$", lines[-1].strip()):
        lines.pop()
        while lines and not lines[-1].strip():
            lines.pop()

    return "\n".join(lines).strip()


# ── PDF rendering ─────────────────────────────────────────────────────────────

def _md_to_pdf(md_text: str, output_path: Path) -> None:
    """Convert Markdown resume text to a clean PDF using fpdf2."""
    from fpdf import FPDF

    pdf = FPDF(format="A4")
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    lines = md_text.splitlines()

    for line in lines:
        stripped = line.strip()

        # ── H1 — candidate name ──────────────────────────────────────────────
        if stripped.startswith("# "):
            text = stripped[2:].strip()
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(17, 17, 17)
            pdf.cell(0, 10, _safe(text), ln=True)
            pdf.set_draw_color(50, 50, 50)
            pdf.set_line_width(0.5)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
            pdf.ln(3)

        # ── H2 — section heading ─────────────────────────────────────────────
        elif stripped.startswith("## "):
            text = stripped[3:].strip().upper()
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, _safe(text), ln=True)
            pdf.set_draw_color(150, 150, 150)
            pdf.set_line_width(0.3)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
            pdf.ln(2)

        # ── H3 — sub-heading ─────────────────────────────────────────────────
        elif stripped.startswith("### "):
            text = stripped[4:].strip()
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 6, _safe(text), ln=True)

        # ── Bullet ───────────────────────────────────────────────────────────
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:].strip()
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(40, 40, 40)
            # Indent + bullet character
            x = pdf.get_x() + 5
            pdf.set_x(x)
            pdf.cell(4, 5, "-", ln=False)
            pdf.multi_cell(0, 5, _safe(_strip_inline_md(text)))
            pdf.set_x(pdf.l_margin)

        # ── Blank line ───────────────────────────────────────────────────────
        elif stripped == "":
            pdf.ln(2)

        # ── Horizontal rule ──────────────────────────────────────────────────
        elif re.match(r"^[-*_]{3,}$", stripped):
            pdf.set_draw_color(180, 180, 180)
            pdf.set_line_width(0.3)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
            pdf.ln(3)

        # ── Normal paragraph ─────────────────────────────────────────────────
        else:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 5, _safe(_strip_inline_md(stripped)))
            pdf.ln(1)

    pdf.output(str(output_path))


def _safe(text: str) -> str:
    """Replace characters that FPDF core fonts can't encode (latin-1 safe)."""
    replacements = {
        "\u2013": "-", "\u2014": "--", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "*", "\u00e2": "a",
        "\u2026": "...",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    # encode to latin-1, replacing anything that can't be represented
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _strip_inline_md(text: str) -> str:
    """Remove bold/italic markers for plain-text rendering."""
    text = re.sub(r"\*\*\*(.+?)\*\*\*", r"\1", text)
    text = re.sub(r"\*\*(.+?)\*\*",     r"\1", text)
    text = re.sub(r"\*(.+?)\*",         r"\1", text)
    text = re.sub(r"`(.+?)`",           r"\1", text)
    return text
