"""
JumpShip — Tailored resume generator.

Pipeline:
  ResumeProfile + JobResult + JobAssessment → LLM → HTML fragment → PDF (xhtml2pdf)

HTML + CSS gives reliable bold/italic and section layout for ATS-style one-page PDFs.
"""
from __future__ import annotations

import html as html_module
import logging
import re
import uuid
from io import BytesIO
from pathlib import Path
from typing import Optional

from pypdf import PdfReader
from xhtml2pdf import pisa

from backend.services.ai_evaluator import (
    compact_tailored_resume_html,
    generate_tailored_resume_html,
)
from backend.services.llm_client import LLMClient

logger = logging.getLogger(__name__)

_MAX_COMPACT_PASSES = 3
# Applied after compaction attempts; shrinks CSS only (content unchanged).
_FONT_SCALES: tuple[float, ...] = (1.0, 0.92, 0.84)


def generate_pdf(
    resume_text: str,
    job_title: str,
    company_name: str,
    job_description: str,
    assessment: Optional[dict] = None,
    output_dir: Optional[Path] = None,
    client: Optional[LLMClient] = None,
    user_profile: Optional[dict] = None,
) -> tuple[Path, str]:
    """
    Generate a tailored resume PDF for a specific job.
    Returns (pdf_path, html_fragment) — the second value is stored in DB column `markdown`.
    """
    from backend.config import settings

    out_dir = output_dir or Path(settings.resume_output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    llm = client or LLMClient.from_settings()
    html_body = generate_tailored_resume_html(
        resume_text=resume_text,
        job_description=job_description,
        job_title=job_title,
        company_name=company_name,
        assessment=assessment,
        client=llm,
        user_profile=user_profile,
    )
    html_body = _sanitize_resume_html(html_body)

    safe_company = re.sub(r"[^\w\-]", "_", company_name or "company")[:30]
    safe_title = re.sub(r"[^\w\-]", "_", job_title or "role")[:30]
    filename = f"resume_{safe_company}_{safe_title}_{uuid.uuid4().hex[:6]}.pdf"
    pdf_path = out_dir / filename

    compact_round = 0
    scale_idx = 0

    while True:
        full_html = _wrap_resume_html_document(html_body, _FONT_SCALES[scale_idx])
        pdf_bytes, pisa_err = _html_to_pdf_bytes(full_html)
        if pisa_err:
            logger.warning("xhtml2pdf reported errors while building resume PDF")
        pages = _pdf_page_count(pdf_bytes)
        if pages <= 1:
            pdf_path.write_bytes(pdf_bytes)
            return pdf_path, html_body

        if compact_round < _MAX_COMPACT_PASSES:
            html_body = _sanitize_resume_html(
                compact_tailored_resume_html(html_body, client=llm)
            )
            compact_round += 1
            continue

        if scale_idx + 1 < len(_FONT_SCALES):
            scale_idx += 1
            continue

        pdf_path.write_bytes(pdf_bytes)
        return pdf_path, html_body


def _sanitize_resume_html(raw: str) -> str:
    """Strip fences, unsafe tags, and keep only #resume-root when possible."""
    text = (raw or "").strip()
    if not text:
        return '<div class="resume" id="resume-root"></div>'

    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].lstrip().startswith("```"):
            lines = lines[1:]
        while lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    footer_re = re.compile(
        r"(?im)^(generated by|created (with|using)|tailored (for|to)|this (resume|cv) (was|is)|"
        r"version\s*\d+|chatgpt|openai|anthropic|claude|gemini|\bai\b.{0,12}assistant|"
        r"disclaimer|notes?:|footer:|compact version|rewritten to fit).*$"
    )
    lines = text.splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    while lines and footer_re.search(lines[-1].strip()):
        lines.pop()
        while lines and not lines[-1].strip():
            lines.pop()
    text = "\n".join(lines).strip()

    from bs4 import BeautifulSoup

    soup = BeautifulSoup(text, "html.parser")
    for tag in soup(["script", "iframe", "object", "embed", "style"]):
        tag.decompose()
    for tag in soup.find_all(True):
        if not getattr(tag, "attrs", None):
            continue
        tag.attrs = {
            k: v
            for k, v in list(tag.attrs.items())
            if not str(k).lower().startswith("on")
        }
        if tag.name == "a" and tag.get("href"):
            href = str(tag["href"]).strip().lower()
            if href.startswith("javascript:"):
                del tag["href"]

    root = soup.select_one("#resume-root")
    if root:
        return str(root)

    inner = soup.body.decode_contents() if soup.body else str(soup)
    if inner.strip():
        return f'<div class="resume" id="resume-root">{inner}</div>'
    esc = html_module.escape(text)
    return f'<div class="resume" id="resume-root"><p>{esc}</p></div>'


def _wrap_resume_html_document(fragment: str, font_scale: float) -> str:
    inner = (fragment or "").strip()
    if "id=\"resume-root\"" not in inner and "id='resume-root'" not in inner:
        inner = f'<div class="resume" id="resume-root">{inner}</div>'

    base = 9.0 * font_scale
    h1 = 15.0 * font_scale
    h2 = 9.5 * font_scale
    h3 = 8.9 * font_scale
    small = 8.15 * font_scale
    li_h = 1.22

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<style>
@page {{ size: A4; margin: 8mm 9mm; }}
* {{ box-sizing: border-box; }}
html {{ font-family: DejaVu Sans, Helvetica, Arial, sans-serif; font-size: {base:.2f}pt; color: #1a1a1a; }}
body {{ margin: 0; padding: 0; }}
#resume-root {{ }}
.hdr {{ margin-bottom: 3pt; }}
.legal-name {{ font-size: {h1:.2f}pt; font-weight: 700; margin: 0 0 2pt 0; }}
.contact-line {{ font-size: {small:.2f}pt; margin: 0; color: #333; line-height: 1.25; }}
section {{ margin-top: 5pt; }}
section:first-of-type {{ margin-top: 3pt; }}
h2 {{
  font-size: {h2:.2f}pt;
  font-weight: 700;
  text-transform: uppercase;
  margin: 0 0 3pt 0;
  padding-bottom: 1.5pt;
  border-bottom: 1px solid #444;
  color: #222;
}}
h3 {{ font-size: {h3:.2f}pt; font-weight: 700; margin: 4pt 0 1pt 0; }}
.job-meta {{ font-size: {small:.2f}pt; margin: 0 0 2pt 0; color: #444; }}
ul {{ margin: 1pt 0 3pt 11pt; padding: 0; }}
li {{ margin-bottom: 1.5pt; line-height: {li_h}; }}
p {{ margin: 1.5pt 0; line-height: 1.24; }}
.skills-block {{ line-height: 1.26; font-size: {small:.2f}pt; }}
strong {{ font-weight: 700; }}
em {{ font-style: italic; }}
</style></head><body>{inner}</body></html>"""


def _html_to_pdf_bytes(html: str) -> tuple[bytes, bool]:
    buf = BytesIO()
    status = pisa.CreatePDF(
        src=html,
        dest=buf,
        encoding="utf-8",
    )
    err = bool(getattr(status, "err", 0))
    return buf.getvalue(), err


def _pdf_page_count(pdf_bytes: bytes) -> int:
    return len(PdfReader(BytesIO(pdf_bytes)).pages)
