from sqlalchemy import Column, String, Float, Boolean, DateTime, Text, JSON, Integer
from sqlalchemy.sql import func
from backend.database import Base
import uuid


def gen_uuid():
    return str(uuid.uuid4())


class SavedJob(Base):
    __tablename__ = "saved_jobs"

    id = Column(String, primary_key=True, default=gen_uuid)
    title = Column(String, nullable=False)
    company_name = Column(String)
    job_url = Column(String)
    job_url_direct = Column(String)
    location_city = Column(String)
    location_state = Column(String)
    location_country = Column(String)
    description = Column(Text)
    job_type = Column(String)
    is_remote = Column(Boolean)
    min_salary = Column(Float)
    max_salary = Column(Float)
    salary_interval = Column(String)
    currency = Column(String)
    site = Column(String)
    company_industry = Column(String)
    job_level = Column(String)
    company_logo = Column(String)
    date_posted = Column(String)
    easy_apply = Column(Boolean)
    saved_at = Column(DateTime, server_default=func.now())
    raw_data = Column(JSON)


class Resume(Base):
    __tablename__ = "resumes"

    id = Column(String, primary_key=True, default=gen_uuid)
    filename = Column(String, nullable=False)
    content = Column(Text, nullable=False)
    file_path = Column(String)
    uploaded_at = Column(DateTime, server_default=func.now())


class Analysis(Base):
    __tablename__ = "analyses"

    id = Column(String, primary_key=True, default=gen_uuid)
    job_id = Column(String, nullable=False)
    resume_id = Column(String, nullable=False)
    job_title = Column(String)
    company_name = Column(String)
    score = Column(Float)
    strengths = Column(JSON)
    gaps = Column(JSON)
    suggestions = Column(JSON)
    summary = Column(Text)
    keywords_matched = Column(JSON)
    keywords_missing = Column(JSON)
    tailored_resume = Column(Text)
    provider = Column(String, default="ollama")
    analyzed_at = Column(DateTime, server_default=func.now())


class Application(Base):
    __tablename__ = "applications"

    id = Column(String, primary_key=True, default=gen_uuid)
    job_id = Column(String)
    job_title = Column(String, nullable=False)
    company_name = Column(String)
    job_url = Column(String)
    site = Column(String)
    status = Column(String, default="saved")  # saved | applied | interviewing | offered | rejected
    applied_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
    notes = Column(Text)
    analysis_id = Column(String, nullable=True)


class UserProfile(Base):
    """Personal information used to pre-fill resume generation context. Stored locally only."""
    __tablename__ = "user_profiles"

    id = Column(String, primary_key=True, default=gen_uuid)

    full_name       = Column(String)
    email           = Column(String)
    phone           = Column(String)
    linkedin_url    = Column(String)
    github_url      = Column(String)
    portfolio_url   = Column(String)
    location_city   = Column(String)
    location_state  = Column(String)
    location_country = Column(String)

    work_authorization  = Column(String)
    willing_to_relocate = Column(Boolean, default=False)
    preferred_work_mode = Column(String)

    years_experience = Column(Integer, default=0)
    highest_degree   = Column(String)
    university       = Column(String)
    graduation_year  = Column(Integer)

    salary_min      = Column(Integer)
    salary_max      = Column(Integer)
    salary_currency = Column(String, default="USD")

    custom_answers  = Column(JSON, default=dict)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class GeneratedResume(Base):
    """Stores per-job tailored resumes generated by the LLM. PDF path on disk."""
    __tablename__ = "generated_resumes"

    id          = Column(String, primary_key=True, default=gen_uuid)
    job_id      = Column(String, index=True)
    job_title   = Column(String, default="")
    company     = Column(String, default="")
    match_score = Column(Integer, default=0)
    markdown    = Column(Text)           # raw LLM markdown output
    pdf_path    = Column(String)         # absolute path to generated PDF on disk
    provider    = Column(String, default="ollama")
    model       = Column(String, default="")
    created_at  = Column(DateTime, server_default=func.now())


class Settings(Base):
    __tablename__ = "settings"

    key = Column(String, primary_key=True)
    value = Column(Text)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
